# Generated by Django 3.2.16 on 2026-03-27 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('home', 'Домашний'), ('foster', 'На передержке')], default='home', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_statuses', to=settings.AUTH_USER_MODEL)),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_status', to='cats.cat')),
            ],
            options={
                'verbose_name': 'Статус владения',
                'verbose_name_plural': 'Статусы владения',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='FosterContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_contracts', to='cats.cat')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Договор передержки',
                'verbose_name_plural': 'Договоры передержки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='fostercontract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('cat',), name='unique_active_foster_contract_per_cat'),
        ),
    ]
